services:
    doctrine.metadata.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ doctrine.metadata.cache ] ]

    doctrine.metadata.cache.config:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ doctrine.metadata.cache.config ] ]
