parameters:
    oro_platform.maintenance.class:               Oro\Bundle\PlatformBundle\Maintenance\Mode
    oro_platform.security.encryptor.mcrypt.class: Oro\Bundle\PlatformBundle\Security\Encryptor\Mcrypt

services:
    oro_platform.maintenance:
        class:                                %oro_platform.maintenance.class%
        arguments:
            - "@lexik_maintenance.driver.factory"
            - "@event_dispatcher"

    oro_platform.security.encryptor.mcrypt:
        class: %oro_platform.security.encryptor.mcrypt.class%
        arguments: [ %kernel.secret% ]
