parameters:
    oro_platform.maintenance.class:                 Oro\Bundle\PlatformBundle\Maintenance\Mode
    oro_platform.event_listener.driver_lock.class:  Oro\Bundle\PlatformBundle\EventListener\Console\DriverLockCommandListener

services:
    oro_platform.maintenance:
        class:                                %oro_platform.maintenance.class%
        arguments:
            - "@lexik_maintenance.driver.factory"
            - "@event_dispatcher"

    oro_platform.event_listener.driver_lock:
        class: %oro_platform.event_listener.driver_lock.class%
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: afterExecute }
