parameters:
    oro_platform.composer.local_repo_manager.class: Oro\Bundle\PlatformBundle\Composer\LocalRepositoryManager
    oro_platform.maintenance.class:                 Oro\Bundle\PlatformBundle\Maintenance\Mode
    oro_platform.event_listener.driver_lock.class:  Oro\Bundle\PlatformBundle\EventListener\Console\DriverLockCommandListener

    oro_platform.composer.config:
        config:
            vendor-dir: ../vendor # we are in web directory, so need to update this path
services:
    oro_platform.maintenance:
        class:                                %oro_platform.maintenance.class%
        arguments:
            - "@lexik_maintenance.driver.factory"
            - "@event_dispatcher"

    oro_platform.event_listener.driver_lock:
        class: %oro_platform.event_listener.driver_lock.class%
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: afterExecute }

    oro_platform.composer.local_repo_manager:
        class: %oro_platform.composer.local_repo_manager.class%
        arguments:
            - @filesystem
            - %kernel.root_dir%/../vendor/
            - 'composer/installed.json'
