parameters:
    oro_platform.maintenance.class:               Oro\Bundle\PlatformBundle\Maintenance\Mode
    oro_platform.command.listener.class:          Oro\Bundle\PlatformBundle\EventListener\Console\CommandListener

services:
    oro_platform.maintenance:
        class:                                %oro_platform.maintenance.class%
        arguments:
            - "@lexik_maintenance.driver.factory"
            - "@event_dispatcher"

    oro_platform.command.listener:
        class: %oro_platform.command.listener.class%
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: afterExecute }
