parameters:
    oro_platform.maintenance.class:           Oro\Bundle\PlatformBundle\Maintenance\Mode
    oro_platform.listener.maintenance.class:  Oro\Bundle\PlatformBundle\EventListener\MaintenanceListener

services:
    oro_platform.maintenance:
        class:                                %oro_platform.maintenance.class%
        arguments:
            - "@lexik_maintenance.driver.factory"
            - "@event_dispatcher"

    kernel.listener.console_maintenance.event:
        class:                                %oro_platform.listener.maintenance.class%
        arguments:
            - "@oro_platform.maintenance"
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandExecute }
